---
#돈에 대한 Data

pay-money: "{0}님에게 {1}을 입금했습니다."

send: "입금완료"

pay-player: "{0}님이 {1}을 입금하셨습니다."

name: "자신을 입력하지마세요!"

laskMoney: "돈이 부족하여 입금 또는 출금 할 수 없습니다."

int: "숫자로 작성해주셔야 합니다."

NoPlayer: "해당 플레이어를 찾지 못했습니다."

...